// <auto-generated />
using System;
using Aurora.SupplyWok.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aurora.SupplyWok.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619231416_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Aggregate.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int")
                        .HasColumnName("current_stock");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_supplies");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int>("InventoryTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_transaction_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("operation_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_inventory_operations");

                    b.HasIndex("InventoryTransactionId")
                        .HasDatabaseName("i_x_inventory_operations_inventory_transaction_id");

                    b.ToTable("inventory_operations", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("reason");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int")
                        .HasColumnName("supply_id");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_inventory_transactions");

                    b.HasIndex("SupplyId")
                        .HasDatabaseName("i_x_inventory_transactions_supply_id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("alert_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("detail");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts", (string)null);

                    b.HasDiscriminator<string>("AlertType").HasValue("Alert");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<double>("LastValue")
                        .HasColumnType("double")
                        .HasColumnName("last_value");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("sensor_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensors");

                    b.ToTable("sensors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 301,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            LastValue = 850.0,
                            MaxValue = 10000.0,
                            MinValue = 0.0,
                            Name = "Main Inventory Weight Sensor",
                            SensorType = "Weight"
                        },
                        new
                        {
                            Id = 302,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Enabled = true,
                            LastValue = 4.0,
                            MaxValue = 8.0,
                            MinValue = -10.0,
                            Name = "Cold Storage Temperature Sensor",
                            SensorType = "Temperature"
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Aggregate.KitchenOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date")
                        .HasColumnName("date_created");

                    b.Property<DateTime?>("HourDelivered")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hour_delivered");

                    b.Property<DateTime?>("HourReady")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("hour_ready");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observations");

                    b.Property<int>("PreparationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("preparation_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("type_service");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_kitchen_orders");

                    b.ToTable("kitchen_orders", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Aggregate.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tables");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("DishCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("dish_category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<bool>("Outstanding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("outstanding");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("p_k_dishes");

                    b.HasIndex("DishCategoryId")
                        .HasDatabaseName("i_x_dishes_dish_category_id");

                    b.ToTable("dishes", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.DishCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("p_k_dish_categories");

                    b.ToTable("dish_categories", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.KitchenOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DishId")
                        .HasColumnType("int")
                        .HasColumnName("dish_id");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dish_name");

                    b.Property<int>("KitchenOrderId")
                        .HasColumnType("int")
                        .HasColumnName("kitchen_order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_kitchen_order_items");

                    b.HasIndex("KitchenOrderId")
                        .HasDatabaseName("i_x_kitchen_order_items_kitchen_order_id");

                    b.ToTable("kitchen_order_items", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Profiles.Domain.Model.Aggregates.RestaurantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("business_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_restaurant_profiles");

                    b.ToTable("restaurant_profiles", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Profiles.Domain.Model.Aggregates.SupplierProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("business_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_supplier_profiles");

                    b.ToTable("supplier_profiles", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("EstimatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estimated_date");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("order_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("restaurant_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_purchase_orders");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_purchase_orders_code");

                    b.ToTable("purchase_orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PO-24021",
                            EstimatedDate = "2026-05-11",
                            OrderDate = "2026-05-10",
                            Priority = "High",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "Pending",
                            SupplierId = 201,
                            SupplierName = "Golden Wok Produce"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PO-24022",
                            EstimatedDate = "2026-05-12",
                            OrderDate = "2026-05-09",
                            Priority = "Medium",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "Confirmed",
                            SupplierId = 202,
                            SupplierName = "Andes Cold Chain"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PO-24023",
                            EstimatedDate = "2026-05-13",
                            OrderDate = "2026-05-08",
                            Priority = "Low",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "InTransit",
                            SupplierId = 203,
                            SupplierName = "Orient Pantry Co."
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_name");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("p_k_purchase_order_items");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("i_x_purchase_order_items_purchase_order_id");

                    b.ToTable("purchase_order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryItemId = 101,
                            ProductName = "Rice",
                            PurchaseOrderId = 1,
                            Quantity = 25m,
                            UnitPrice = 4.5m,
                            UnitType = "kg"
                        },
                        new
                        {
                            Id = 2,
                            InventoryItemId = 102,
                            ProductName = "Soy Sauce",
                            PurchaseOrderId = 1,
                            Quantity = 12m,
                            UnitPrice = 8.2m,
                            UnitType = "ltr"
                        },
                        new
                        {
                            Id = 3,
                            InventoryItemId = 103,
                            ProductName = "Chicken Breast",
                            PurchaseOrderId = 2,
                            Quantity = 18m,
                            UnitPrice = 14.8m,
                            UnitType = "kg"
                        },
                        new
                        {
                            Id = 4,
                            InventoryItemId = 104,
                            ProductName = "Sesame Oil",
                            PurchaseOrderId = 3,
                            Quantity = 6m,
                            UnitPrice = 18.4m,
                            UnitType = "ltr"
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryConditions")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("delivery_conditions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_catalog_items");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("i_x_catalog_items_supplier_id");

                    b.ToTable("catalog_items", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("district");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("LinkedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("linked_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ResponseTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("response_time");

                    b.Property<string>("Sla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sla");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_suppliers_uuid");

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Category = "Grains and pantry",
                            ContactName = "Mariela Soto",
                            Email = "msoto@goldenwok.pe",
                            LinkedDate = "2026-04-21",
                            Name = "Golden Wok Produce",
                            Phone = "+51 999 111 222",
                            ResponseTime = "1.6 H",
                            Sla = "98% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111201")
                        },
                        new
                        {
                            Id = 202,
                            Category = "Cold products",
                            ContactName = "Luis Cardenas",
                            Email = "lcardenas@andescold.pe",
                            LinkedDate = "2026-04-20",
                            Name = "Andes Cold Chain",
                            Phone = "+51 999 333 444",
                            ResponseTime = "2.1 H",
                            Sla = "95% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111202")
                        },
                        new
                        {
                            Id = 203,
                            Category = "Asian sauces and oils",
                            ContactName = "Zhen Liu",
                            Email = "zliu@orientpantry.pe",
                            LinkedDate = "2026-04-19",
                            Name = "Orient Pantry Co.",
                            Phone = "+51 999 555 666",
                            ResponseTime = "2.9 H",
                            Sla = "91% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111203")
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.SupplierClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_supplier_clients");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("i_x_supplier_clients_client_id");

                    b.HasIndex("SupplierId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("i_x_supplier_clients_supplier_id_client_id");

                    b.ToTable("supplier_clients", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertRestaurant", b =>
                {
                    b.HasBaseType("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_alerts_sensor_id");

                    b.ToTable("alerts");

                    b.HasDiscriminator().HasValue("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 301,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2026, 6, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "Inventory stock differs from main inventory weight sensor.",
                            Severity = "Medium",
                            Status = "Pending",
                            SensorId = 301
                        },
                        new
                        {
                            Id = 302,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "Cold storage temperature is outside the expected range.",
                            Severity = "High",
                            Status = "Pending",
                            SensorId = 302
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertSupplier", b =>
                {
                    b.HasBaseType("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert");

                    b.ToTable("alerts");

                    b.HasDiscriminator().HasValue("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 303,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Date = new DateTimeOffset(new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Detail = "Supplier delivery status should be reviewed.",
                            Severity = "Low",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryOperation", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryTransaction", "InventoryTransaction")
                        .WithMany("Operations")
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k__inventory_operations__inventory_transactions");

                    b.Navigation("InventoryTransaction");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Aggregate.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k__inventory_transactions__supplies");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.Dish", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.DishCategory", "DishCategory")
                        .WithMany()
                        .HasForeignKey("DishCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_dishes__dish_categories_dish_category_id");

                    b.Navigation("DishCategory");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Entities.KitchenOrderItem", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Operations.Domain.Model.Aggregate.KitchenOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("KitchenOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_kitchen_order_items_kitchen_orders_kitchen_order_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Profiles.Domain.Model.Aggregates.RestaurantProfile", b =>
                {
                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("RestaurantProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("district");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("street");

                            b1.HasKey("RestaurantProfileId")
                                .HasName("p_k_restaurant_profiles");

                            b1.ToTable("restaurant_profiles");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantProfileId")
                                .HasConstraintName("f_k_restaurant_profiles_restaurant_profiles_id");
                        });

                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "ContactEmail", b1 =>
                        {
                            b1.Property<int>("RestaurantProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("contact_email");

                            b1.HasKey("RestaurantProfileId")
                                .HasName("p_k_restaurant_profiles");

                            b1.ToTable("restaurant_profiles");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantProfileId")
                                .HasConstraintName("f_k_restaurant_profiles_restaurant_profiles_id");
                        });

                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "ContactName", b1 =>
                        {
                            b1.Property<int>("RestaurantProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("contact_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("contact_last_name");

                            b1.HasKey("RestaurantProfileId")
                                .HasName("p_k_restaurant_profiles");

                            b1.ToTable("restaurant_profiles");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantProfileId")
                                .HasConstraintName("f_k_restaurant_profiles_restaurant_profiles_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactEmail")
                        .IsRequired();

                    b.Navigation("ContactName")
                        .IsRequired();
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Profiles.Domain.Model.Aggregates.SupplierProfile", b =>
                {
                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("SupplierProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("district");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("street");

                            b1.HasKey("SupplierProfileId")
                                .HasName("p_k_supplier_profiles");

                            b1.ToTable("supplier_profiles");

                            b1.WithOwner()
                                .HasForeignKey("SupplierProfileId")
                                .HasConstraintName("f_k_supplier_profiles_supplier_profiles_id");
                        });

                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "ContactEmail", b1 =>
                        {
                            b1.Property<int>("SupplierProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("contact_email");

                            b1.HasKey("SupplierProfileId")
                                .HasName("p_k_supplier_profiles");

                            b1.ToTable("supplier_profiles");

                            b1.WithOwner()
                                .HasForeignKey("SupplierProfileId")
                                .HasConstraintName("f_k_supplier_profiles_supplier_profiles_id");
                        });

                    b.OwnsOne("Aurora.SupplyWok.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "ContactName", b1 =>
                        {
                            b1.Property<int>("SupplierProfileId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("contact_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("varchar(60)")
                                .HasColumnName("contact_last_name");

                            b1.HasKey("SupplierProfileId")
                                .HasName("p_k_supplier_profiles");

                            b1.ToTable("supplier_profiles");

                            b1.WithOwner()
                                .HasForeignKey("SupplierProfileId")
                                .HasConstraintName("f_k_supplier_profiles_supplier_profiles_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ContactEmail")
                        .IsRequired();

                    b.Navigation("ContactName")
                        .IsRequired();
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_purchase_order_items_purchase_orders_purchase_order_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.CatalogItem", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_catalog_items__suppliers_supplier_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.SupplierClient", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_supplier_clients_clients_client_id");

                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_supplier_clients_suppliers_supplier_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertRestaurant", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.InventoryTransaction", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Aggregate.KitchenOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
