// <auto-generated />
using System;
using Aurora.SupplyWok.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aurora.SupplyWok.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Aggregate.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int")
                        .HasColumnName("current_stock");

                    b.Property<int>("MinimumStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_supplies");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("reason");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int")
                        .HasColumnName("supply_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_stock_movements");

                    b.HasIndex("SupplyId")
                        .HasDatabaseName("i_x_stock_movements_supply_id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("alert_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("date");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("detail");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts", (string)null);

                    b.HasDiscriminator<string>("AlertType").HasValue("Alert");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<double>("LastValue")
                        .HasColumnType("double")
                        .HasColumnName("last_value");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sensor_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensors");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Operations.Domain.Model.Aggregate.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tables");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("EstimatedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("estimated_date");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("order_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("restaurant_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_purchase_orders");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_purchase_orders_code");

                    b.ToTable("purchase_orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PO-24021",
                            EstimatedDate = "2026-05-11",
                            OrderDate = "2026-05-10",
                            Priority = "High",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "Pending",
                            SupplierId = 201,
                            SupplierName = "Golden Wok Produce"
                        },
                        new
                        {
                            Id = 2,
                            Code = "PO-24022",
                            EstimatedDate = "2026-05-12",
                            OrderDate = "2026-05-09",
                            Priority = "Medium",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "Confirmed",
                            SupplierId = 202,
                            SupplierName = "Andes Cold Chain"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PO-24023",
                            EstimatedDate = "2026-05-13",
                            OrderDate = "2026-05-08",
                            Priority = "Low",
                            RestaurantName = "Gran Dragon Chifa",
                            Status = "InTransit",
                            SupplierId = 203,
                            SupplierName = "Orient Pantry Co."
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_name");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit_type");

                    b.HasKey("Id")
                        .HasName("p_k_purchase_order_items");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("i_x_purchase_order_items_purchase_order_id");

                    b.ToTable("purchase_order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryItemId = 101,
                            ProductName = "Rice",
                            PurchaseOrderId = 1,
                            Quantity = 25m,
                            UnitPrice = 4.5m,
                            UnitType = "kg"
                        },
                        new
                        {
                            Id = 2,
                            InventoryItemId = 102,
                            ProductName = "Soy Sauce",
                            PurchaseOrderId = 1,
                            Quantity = 12m,
                            UnitPrice = 8.2m,
                            UnitType = "ltr"
                        },
                        new
                        {
                            Id = 3,
                            InventoryItemId = 103,
                            ProductName = "Chicken Breast",
                            PurchaseOrderId = 2,
                            Quantity = 18m,
                            UnitPrice = 14.8m,
                            UnitType = "kg"
                        },
                        new
                        {
                            Id = 4,
                            InventoryItemId = 104,
                            ProductName = "Sesame Oil",
                            PurchaseOrderId = 3,
                            Quantity = 6m,
                            UnitPrice = 18.4m,
                            UnitType = "ltr"
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryConditions")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("delivery_conditions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_catalog_items");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("i_x_catalog_items_supplier_id");

                    b.ToTable("catalog_items", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("district");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("category");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("LinkedDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("linked_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<string>("ResponseTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("response_time");

                    b.Property<string>("Sla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sla");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_suppliers_uuid");

                    b.ToTable("suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Category = "Grains and pantry",
                            ContactName = "Mariela Soto",
                            Email = "msoto@goldenwok.pe",
                            LinkedDate = "2026-04-21",
                            Name = "Golden Wok Produce",
                            Phone = "+51 999 111 222",
                            ResponseTime = "1.6 H",
                            Sla = "98% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111201")
                        },
                        new
                        {
                            Id = 202,
                            Category = "Cold products",
                            ContactName = "Luis Cardenas",
                            Email = "lcardenas@andescold.pe",
                            LinkedDate = "2026-04-20",
                            Name = "Andes Cold Chain",
                            Phone = "+51 999 333 444",
                            ResponseTime = "2.1 H",
                            Sla = "95% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111202")
                        },
                        new
                        {
                            Id = 203,
                            Category = "Asian sauces and oils",
                            ContactName = "Zhen Liu",
                            Email = "zliu@orientpantry.pe",
                            LinkedDate = "2026-04-19",
                            Name = "Orient Pantry Co.",
                            Phone = "+51 999 555 666",
                            ResponseTime = "2.9 H",
                            Sla = "91% SLA",
                            Uuid = new Guid("11111111-1111-1111-1111-111111111203")
                        });
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.SupplierClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_supplier_clients");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("i_x_supplier_clients_client_id");

                    b.HasIndex("SupplierId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("i_x_supplier_clients_supplier_id_client_id");

                    b.ToTable("supplier_clients", (string)null);
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertRestaurant", b =>
                {
                    b.HasBaseType("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("i_x_alerts_sensor_id");

                    b.ToTable("alerts");

                    b.HasDiscriminator().HasValue("Restaurant");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertSupplier", b =>
                {
                    b.HasBaseType("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Alert");

                    b.ToTable("alerts");

                    b.HasDiscriminator().HasValue("Supplier");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Entities.StockMovement", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Inventory.Domain.Model.Aggregate.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_stock_movements_supplies_supply_id");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_purchase_order_items_purchase_orders_purchase_order_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.CatalogItem", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_catalog_items__suppliers_supplier_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.SupplierClient", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_supplier_clients_clients_client_id");

                    b.HasOne("Aurora.SupplyWok.Platform.Suppliers.Domain.Model.Aggregates.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_supplier_clients_suppliers_supplier_id");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Iot.Domain.Model.Entities.AlertRestaurant", b =>
                {
                    b.HasOne("Aurora.SupplyWok.Platform.Iot.Domain.Model.Aggregate.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alerts_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Aurora.SupplyWok.Platform.Purchasing.Domain.Model.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}


